### PR TITLE
podspec for iOS

### PR DESCRIPTION
**Pull request by banjun**
I want to use this on iOS via CocoaPods.

### CODE REVIEW

**Comment by banjun** [comment]
@kareman Thank you for merging 😄 
Do you have a plan to `pod trunk push`?
Is the pod in trunk not owned by you?? https://cocoapods.org/?q=footlessparser
We can use the updated pod also in podspec dependency (not only in Podfile) if it were in trunk.

**Comment by kareman** [comment]
No the pod in trunk is not mine. It points to oleander's clone of this repository. I have very little experience with pods, any idea what to do if I want to push to trunk? Will I have to choose a different name?

**Comment by banjun** [comment]
I've looked around some points.
pod trunk has the pod named FootlessParser and this is not owned by you. (and its versioning is different than your repo.)

https://github.com/CocoaPods/Specs/tree/master/Specs/0/9/4/FootlessParser

Since pod trunk treats names of pods as an identifier, the most simple way is that you choose a difference name to publish this repo to pod trunk. (A pod owner is the first person who `pod trunk push`  a pod with the name of pod.)

If this is the first time you publish a pod, you can publish this pod with `pod trunk register ...` & `pod trunk push ...`, as the guide is below.
Because renaming is needed, you'll have to modify `s.name` in `FootlessParser.podspec` before the trunk push.

https://guides.cocoapods.org/making/getting-setup-with-trunk.html

Alternatively, you can also claim naming at `Claiming an existing library` form in above link...

**Comment by kareman** [comment]
Well I would prefer to use the FootlessParser name for the pod too. But oleander's pod has the version 2.0.6, and I'm about to release version 0.4. All pods that have FootlessParser as a dependency are made by oleander too, but what about other projects that use oleander's pod? Won't they be confused when the version of the pod goes from 2.0.6 to 0.4? I could of course just go directly to version 3, but I don't fell like this project is that mature yet.

**Comment by banjun** [comment]
I think it's natural to use the original name ❤️ 
But I think you'll need to take ownership of the current pod from oleander 😕 

After that the versioning problem arise as you point out.
Once you push `0.4` to pod trunk, trunk have 2 versions, 0.4 & 2.0.6. Most podspecs & Podfiles that use `~> 2.0` or `= 2.0.6` version requirements should not be affected this time. Reinstalling their pod dependencies choose 2.0.6.
Next you can delete 2.0.6 using pod trunk delete, letting trunk have 1 version, 0.4. This cause error on reinstalling their pod dependencies (such like version ~> 2.0 not found). They'll have to migrate to another pod name, or specify git repo url in their Podfile.
Finally `pod "FootlessParser"` will install the only & latest version `0.4`. You can add successive versions anytime.

**Comment by kareman** [comment]
I have asked oleander if he is willing to hand over ownership of the pod.

**Comment by kareman** [comment]
oleander has gracefully added me as a owner of the pod, so I am ready to release version 0.4 to trunk. But first, could you @banjun verify that the latest commit to this repository works fine with CocoaPods and can be integrated into an iOS project?

**Comment by banjun** [comment]
great news!
I've confirmed with my project that pod install works fine to use current master a335a59. refs https://github.com/banjun/NorthLayout/commit/3c7d21bd1e29006e57a361d5c386e53e7d681825

**Comment by kareman** [comment]
Okay I have pushed version 0.4 to trunk. I haven't done anything with version 2.0.6 yet because I'm waiting to find out if anyone else is using it. I feel like I should probably give them a heads up first.

**Comment by banjun** [comment]
Many thanks to you & oleander 🎉 
Now I can remove the repo specifier in Podfile and pass pod trunk validation to push my podspec, which has dependency to FootlessParser ~> 0.4 in the trunk.

**Comment by kareman** [comment]
Nice. I like your usage of FootlessParser so I added your library to the list of examples in the readme and updated the instructions for using FootlessParser in a podfile.

**Comment by banjun** [comment]
😄 👍

**Pull request merged**
